# File operations and directory structure (existing settings)
output_format: "xlsx"
csv_delimiter: ";"
encoding: "utf-8"
quoting: 1
include_timestamp: true
logging_level: "INFO"
disable_logging: false

directory_structure:
  data:
    - raw
    - configurations
    - interim
    - processed
  reports:
    - figures
    - outputs
  models: []
  src: []

# New semantic analyzer settings
semantic_analyzer:
  default_language: "en"
  content_column: "content"
  
  # Analysis settings
  analysis:
    keywords:
      max_keywords: 10
      min_keyword_length: 3
      include_compounds: true
    
    themes:
      max_themes: 3
      min_confidence: 0.5
      include_hierarchy: true
    
    categories:
      max_categories: 3
      min_confidence: 0.3
      require_evidence: true
  
  # Model settings
  models:
    default_provider: "openai"
    default_model: "gpt-4o-mini"
    parameters:
      temperature: 0.0
      max_tokens: 1000
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
  
  # Feature flags
  features:
    use_caching: true
    use_async: true
    use_batching: true
    enable_finnish_support: true